CREATE TABLE healthcare_data (
    patient_id INT,
    age INT,
    age_group VARCHAR(50),
    gender VARCHAR(20),
    state VARCHAR(50),
    city VARCHAR(50),
    region VARCHAR(50),
    urban_rural VARCHAR(20),
    disease_name VARCHAR(100),
    disease_category VARCHAR(100),
    severity VARCHAR(20),
    diagnosis_date DATE,
    month VARCHAR(20),
    season VARCHAR(20),
    bmi FLOAT,
    smoking_status VARCHAR(20),
    alcohol_use VARCHAR(20),
    blood_group VARCHAR(10),
    comorbidity VARCHAR(100),
    treatment_type VARCHAR(50),
    hospital_type VARCHAR(50),
    insurance_status VARCHAR(50),
    income_level VARCHAR(50),
    days_hospitalized INT,
    treatment_cost_inr FLOAT,
    recovery_days INT,
    outcome VARCHAR(50),
    death_flag INT,
    cause_of_death VARCHAR(100),
    follow_up_required VARCHAR(20)
);
drop table
select * from healthcare_data;